name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.6.0-alpine3.11
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release