name: example using custom JS action

on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'Obama'
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
